name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space on GitHub Runner
      uses: easimon/maximize-build-space@v10
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Configure Docker Storage Directory
      run: |
        sudo systemctl stop docker.service docker.socket
        sudo mkdir -p /buildspace/docker
        if [ -d "/var/lib/docker" ]; then
          sudo cp -rp /var/lib/docker/* /buildspace/docker/ 2>/dev/null || true
          sudo rm -rf /var/lib/docker
        fi
        sudo ln -s /buildspace/docker /var/lib/docker
        sudo systemctl start docker.service

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        no-cache: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flux-serverless:v1